import express from 'express';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

import { HttpError, toHttpError } from './http-errors.js';
import calculateRouter from './routes/calculate.js';
import settingsRouter from './routes/settings.js';
import vrmRouter from './routes/vrm.js';

const app = express();
app.disable('x-powered-by');

const __dirname = dirname(fileURLToPath(import.meta.url));
const staticDir = join(__dirname, '../app');

const rawPort = Number.parseInt(process.env.PORT ?? '', 10);
const port = Number.isFinite(rawPort) ? rawPort : 3000;
const host = process.env.HOST ?? '0.0.0.0';

app.use(express.json({ limit: '1mb' }));

app.use('/calculate', calculateRouter);
app.use('/settings', settingsRouter);
app.use('/vrm', vrmRouter);

app.get('/runtime-config.js', (_req, res) => {
  res.set('Cache-Control', 'no-store');
  res.type('application/javascript').send(`
// Generated by the API server
export const BACKEND_MODE = "api";
export const API_BASE_URL = "${process.env.API_BASE_URL ?? `http://${host === '0.0.0.0' ? 'localhost' : host}:${port}`}";
`);
});

app.get('/health', (_req, res) => {
  res.json({ message: 'Optivolt API is running.' });
});

app.use(express.static(staticDir));

app.use((req, res, next) => {
  next(new HttpError(404, 'Not found'));
});

app.use((err, req, res, _next) => {
  const httpError = toHttpError(err);
  const status = httpError.statusCode ?? 500;

  if (status >= 500) {
    console.error(`Unhandled error for ${req.method} ${req.originalUrl}:`, err);
  }

  const payload = { error: httpError.message };
  if (httpError.expose && httpError.details) {
    payload.details = httpError.details;
  }

  res.status(status).json(payload);
});

app.listen(port, host, () => {
  console.log(`Server listening on http://${host === '0.0.0.0' ? 'localhost' : host}:${port}`);
});
