# Check API status
GET http://localhost:3000/health

### Calculation all
POST http://localhost:3000/calculate
Content-Type: application/json

{
  "updateData": true
}

### Calculation next quarter
POST http://localhost:3000/calculate/next-quarter
Content-Type: application/json

{
  "updateData": true,
  "socNow_percent": 52.3
}



### Settings (confirm what /calculate will read)
GET http://localhost:3000/settings
