# Check API status
GET http://localhost:3000/

### Calculation
# Uses settings persisted via /settings/* endpoints
POST http://localhost:3000/calculate
Content-Type: application/json

{
  "timing": {
    "startMs": 1700000000000,
    "stepMin": 15
  }
}

### System settings
GET http://localhost:3000/settings/system

POST http://localhost:3000/settings/system
Content-Type: application/json

{
  "stepSize_m": 15,
  "batteryCapacity_Wh": 20480,
  "minSoc_percent": 20,
  "maxSoc_percent": 100,
  "initialSoc_percent": 20,
  "maxChargePower_W": 3600,
  "maxDischargePower_W": 4000,
  "maxGridImport_W": 2500,
  "maxGridExport_W": 5000,
  "chargeEfficiency_percent": 95,
  "dischargeEfficiency_percent": 95,
  "batteryCost_cent_per_kWh": 2
}

### Algorithm settings
GET http://localhost:3000/settings/algorithm

POST http://localhost:3000/settings/algorithm
Content-Type: application/json

{
  "terminalSocValuation": "zero",
  "terminalSocCustomPrice_cents_per_kWh": 0
}

### Time series
GET http://localhost:3000/settings/time-series

POST http://localhost:3000/settings/time-series
Content-Type: application/json

{
  "load_W_txt": "280,250,360,420",
  "pv_W_txt": "0,0,0,0",
  "importPrice_txt": "20,20,30,30",
  "exportPrice_txt": "5,5,6,6",
  "tsStart": "2024-01-01T00:00",
  "tableShowKwh": false
}
